import { useMemo,useState } from 'react'
import QRCode from 'qrcode'
import { FileSpreadsheet,Loader2,Printer,QrCode } from 'lucide-react'
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select'
import { formatEquipmentQrDisplayCode,getServerCompatibleLabelSize,validateBatchInput,type EquipmentQrBatchInput,type EquipmentQrLabel,type EquipmentQrLabelSize } from '@/lib/equipment-qr-labels'
import { downloadZebraWorkbook,isLocalLabelUrl } from '@/lib/equipment-qr-xlsx'
import { blobToDataUrl,renderEquipmentQrLabelPng } from '@/lib/equipment-qr-label-renderer'
import { QR_LABEL_LOGO_SRC } from '@/config/branding'
import { supabase } from '@/lib/supabase'

const initialInput:EquipmentQrBatchInput={quantity:100,startNumber:1,prefix:'',digits:3,labelSize:'100x40',columns:1}
type Printable=EquipmentQrLabel&{qrDataUrl:string;labelPng:Blob;labelPngDataUrl:string}

export function EquipmentQrBatchDialog({open,onOpenChange}:{open:boolean;onOpenChange:(open:boolean)=>void}){
 const [input,setInput]=useState(initialInput),[labels,setLabels]=useState<Printable[]>([]),[busy,setBusy]=useState(false),[exportBusy,setExportBusy]=useState(false),[message,setMessage]=useState(''),[printMode,setPrintMode]=useState<'batch'|'calibration'>('batch'),[calibrationPng,setCalibrationPng]=useState('')
 const errors=useMemo(()=>validateBatchInput(input),[input]),first=formatEquipmentQrDisplayCode(input.startNumber,input.digits,input.prefix),last=formatEquipmentQrDisplayCode(input.startNumber+Math.max(0,input.quantity-1),input.digits,input.prefix)
 const update=<K extends keyof EquipmentQrBatchInput>(key:K,value:EquipmentQrBatchInput[K])=>{setInput(current=>({...current,[key]:value,...(key==='labelSize'&&value==='100x40'?{columns:1}:{})}));setLabels([]);setMessage('')}
 const generate=async()=>{
  if(errors.length||busy)return;setBusy(true);setLabels([]);setMessage('')
  try{
   const {data:sessionData}=await supabase.auth.getSession();if(!sessionData.session?.access_token)throw new Error('session')
   const {data:userData,error:userError}=await supabase.auth.getUser();if(userError||!userData.user)throw new Error('jwt')
   const serverInput={...input,labelSize:getServerCompatibleLabelSize(input.labelSize)}
   const {data,error}=await supabase.functions.invoke('equipment-qr-admin',{body:{action:'generate-batch',...serverInput}})
   if(error){if(error.context?.status===409)throw new Error('duplicate');throw new Error('request')}
   if(!Array.isArray(data?.labels)||data.labels.length!==input.quantity)throw new Error('partial')
   const printable:Printable[]=[]
   for(const label of data.labels as EquipmentQrLabel[]){if(typeof label.publicUrl!=='string')throw new Error('dto');const qrDataUrl=await QRCode.toDataURL(label.publicUrl,{margin:4,width:512,errorCorrectionLevel:'M'});const labelPng=await renderEquipmentQrLabelPng(qrDataUrl,label.displayCode,QR_LABEL_LOGO_SRC,input.labelSize);printable.push({...label,qrDataUrl,labelPng,labelPngDataUrl:await blobToDataUrl(labelPng)})}
   setLabels(printable);setMessage(`${printable.length} etiquetas geradas com segurança.`)
  }catch(error){setLabels([]);setMessage(error instanceof Error&&error.message==='duplicate'?'Já existem etiquetas dentro da numeração informada. Ajuste o número inicial ou o prefixo.':'Não foi possível gerar o lote. Verifique sua sessão e tente novamente.')}
  finally{setBusy(false)}
 }
 const hasLocalUrls=labels.some(label=>isLocalLabelUrl(label.publicUrl??''))
 const downloadExcel=async()=>{if(!labels.length||exportBusy)return;setExportBusy(true);setMessage('Preparando etiquetas...');try{const processed:Printable[]=[];for(const label of labels){const labelPng=await renderEquipmentQrLabelPng(label.qrDataUrl,label.displayCode,QR_LABEL_LOGO_SRC,input.labelSize);processed.push({...label,labelPng,labelPngDataUrl:await blobToDataUrl(labelPng)})}const fileName=await downloadZebraWorkbook(processed,input.columns,input.labelSize);setMessage(`${fileName} baixado com sucesso.`)}catch{setMessage('Não foi possível processar todas as imagens. O download foi cancelado e nenhuma etiqueta ou token foi alterado.')}finally{setExportBusy(false)}}
 const printBatch=()=>{setPrintMode('batch');setTimeout(()=>window.print(),0)}
 const printCalibration=async()=>{if(busy||exportBusy)return;if(!window.confirm('No driver da impressora Zebra, selecione papel 100 × 40 mm, escala 100% e desative Ajustar à página.\n\nContinuar com a impressão de teste?'))return;setExportBusy(true);try{const png=await renderEquipmentQrLabelPng(null,'001',QR_LABEL_LOGO_SRC,'100x40',true);setCalibrationPng(await blobToDataUrl(png));setPrintMode('calibration');setMessage('Prévia de calibração pronta. Nenhum token ou registro foi criado.');setTimeout(()=>window.print(),0)}catch{setMessage('Não foi possível preparar a etiqueta de calibração. Nenhum registro foi criado.')}finally{setExportBusy(false)}}
 const previewCodes=first===last?[first]:[first,last]
 const printSize=printMode==='calibration'?'100x40':input.labelSize,printSelector=printMode==='calibration'?'.equipment-qr-calibration-preview':'.equipment-qr-print-preview'
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="flex max-h-[92vh] w-[calc(100vw-2rem)] max-w-4xl flex-col overflow-hidden rounded-2xl"><DialogHeader><DialogTitle>Gerar etiquetas QR</DialogTitle><DialogDescription>Configure e revise o lote antes de criar tokens reais.</DialogDescription></DialogHeader>
  <div className="min-h-0 flex-1 space-y-4 overflow-y-auto pr-1">
   <div className="grid gap-4 sm:grid-cols-3"><Field label="Quantidade"><Input type="number" min={1} max={500} step={1} value={input.quantity} onChange={e=>update('quantity',Number(e.target.value))}/></Field><Field label="Número inicial"><Input type="number" min={1} step={1} value={input.startNumber} onChange={e=>update('startNumber',Number(e.target.value))}/></Field><Field label="Prefixo opcional"><Input maxLength={12} value={input.prefix} onChange={e=>update('prefix',e.target.value.toUpperCase())}/></Field><Field label="Dígitos"><Input type="number" min={1} max={8} step={1} value={input.digits} onChange={e=>update('digits',Number(e.target.value))}/></Field><Field label="Tamanho"><Select value={input.labelSize} onValueChange={(v:EquipmentQrLabelSize)=>update('labelSize',v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="100x40">100 × 40 mm</SelectItem><SelectItem value="60x40">60 × 40 mm</SelectItem><SelectItem value="50x30">50 × 30 mm</SelectItem><SelectItem value="80x50">80 × 50 mm</SelectItem></SelectContent></Select>{input.labelSize==='100x40'&&<p className="text-xs text-slate-600">Formato para etiqueta Zebra: uma etiqueta por linha.</p>}</Field><Field label="Colunas"><Input type="number" min={1} max={5} step={1} value={input.columns} disabled={input.labelSize==='100x40'} onChange={e=>update('columns',Number(e.target.value))}/></Field></div>
   <p className="text-xs font-medium text-amber-700">Confirme as dimensões do papel com uma régua antes de imprimir o lote definitivo.</p>
   <div className="rounded-xl bg-slate-50 p-3 text-sm"><b>{errors.length?'Corrija os campos':`${first} até ${last}`}</b>{errors.map(error=><p className="text-red-600" key={error}>{error}</p>)}{hasLocalUrls&&<p className="mt-2 font-medium text-amber-700">ETIQUETAS DE TESTE: os QR Codes utilizam localhost e não funcionarão em outros dispositivos. Gere as etiquetas definitivas somente após configurar a URL pública da aplicação.</p>}{message&&<p className="mt-2 font-medium">{message}</p>}</div>
   <section aria-label="Prévia do lote"><div className="mb-2 flex items-center justify-between"><h3 className="text-sm font-bold text-slate-900">Prévia do lote</h3><span className="text-xs text-slate-500">{labels.length?'Etiquetas reais':'QR ilustrativo — nenhum token criado'}</span></div>
    <div className="equipment-qr-print-preview relative grid max-h-80 gap-3 overflow-y-auto rounded-xl border bg-slate-100 p-3">{busy&&<div className="absolute inset-0 z-10 flex items-center justify-center gap-2 rounded-xl bg-white/90 font-semibold"><Loader2 className="h-5 w-5 animate-spin"/>Gerando etiquetas…</div>}{labels.length?labels.map(item=><QrLabel key={item.id} code={item.displayCode} size={input.labelSize} labelPngDataUrl={item.labelPngDataUrl}/>):previewCodes.map((code,index)=><QrLabel key={`${code}-${index}`} code={code} size={input.labelSize} preview/>)}</div>
    <p className="mt-2 text-center text-xs text-slate-500">{input.labelSize.replace('x',' × ')} mm — escala de visualização reduzida</p>
   </section>
   {calibrationPng&&<div className="equipment-qr-calibration-preview hidden"><QrLabel code="001" size="100x40" labelPngDataUrl={calibrationPng}/></div>}
  </div>
  <DialogFooter className="border-t pt-4"><Button type="button" variant="ghost" onClick={printCalibration} disabled={busy||exportBusy}>Imprimir etiqueta de teste</Button><Button type="button" variant="outline" onClick={downloadExcel} disabled={!labels.length||busy||exportBusy}>{exportBusy?<Loader2 className="h-4 w-4 animate-spin"/>:<FileSpreadsheet className="h-4 w-4"/>}{exportBusy?'Preparando etiquetas...':'Baixar Excel'}</Button><Button type="button" variant="outline" onClick={printBatch} disabled={!labels.length||busy||exportBusy}><Printer className="h-4 w-4"/>Imprimir lote</Button><Button type="button" onClick={generate} disabled={busy||exportBusy||errors.length>0}>{busy?<><Loader2 className="h-4 w-4 animate-spin"/>Gerando etiquetas…</>:'Confirmar geração'}</Button></DialogFooter>
  <style>{`@page{size:${printSize.replace('x','mm ')}mm;margin:0}@media print{html,body{margin:0!important;padding:0!important}body *{visibility:hidden!important}${printSelector},${printSelector} *{visibility:visible!important}${printSelector}{display:block!important;position:absolute!important;left:0!important;top:0!important;width:${printSize.split('x')[0]}mm!important;max-height:none!important;overflow:visible!important;border:0!important;padding:0!important;margin:0!important;background:#fff!important}${printSelector} .equipment-qr-print-label{display:block!important;width:${printSize.split('x')[0]}mm!important;height:${printSize.split('x')[1]}mm!important;box-sizing:border-box!important;overflow:hidden!important;break-after:page!important;page-break-after:always!important;break-inside:avoid!important;page-break-inside:avoid!important;margin:0!important}${printSelector} .equipment-qr-print-label:last-child{break-after:auto!important;page-break-after:auto!important}}`}</style>
 </DialogContent></Dialog>
}

function QrLabel({code,size,preview=false,labelPngDataUrl}:{code:string;size:EquipmentQrLabelSize;preview?:boolean;labelPngDataUrl?:string}){const [w,h]=size.split('x').map(Number);if(!preview&&labelPngDataUrl)return <article className="equipment-qr-print-label mx-auto w-full max-w-sm overflow-hidden bg-white" style={{aspectRatio:`${w}/${h}`}}><img src={labelPngDataUrl} alt={`Etiqueta patrimonial ${code}`} className="h-full w-full object-contain"/></article>;return <article className="equipment-qr-print-label mx-auto grid w-full max-w-sm grid-cols-[40%_60%] items-center overflow-hidden rounded-md border border-slate-300 bg-white p-2 text-slate-950" style={{aspectRatio:`${w}/${h}`}}><div className="flex h-full items-center justify-center p-1"><div className="flex aspect-square w-full max-w-28 flex-col items-center justify-center rounded border border-dashed border-slate-400 text-slate-400"><QrCode className="h-10 w-10"/><small>PRÉVIA</small></div></div><div className="flex min-w-0 flex-col items-center justify-center gap-1 px-2 text-center"><img src={QR_LABEL_LOGO_SRC} alt="CONCREM" className="h-10 w-full object-contain"/><span className="text-[10px] font-bold tracking-wide">PATRIMÔNIO</span><strong className="max-w-full break-all font-mono text-xl leading-none">{code}</strong></div></article>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
